### ISSUE TITLE
Special characters in translation

### ISSUE THREAD

**Issue by robinvdijk** [translation/rails#25]
If I write the following segments 

    example_one: It is equal to 3
    example_two: It is > 3
    example_three: It is too big

 then the YAML that gets produced becomes

    example_one: It is equal to 3
    example_two: It is
      > 3
    example_three: It is too big

To get it the created YAML on one line, I can wrap the text in the segment in quotation marks, but then the produced YAML will become:

    example_one: It is equal to 3
    example_two: '"It is > 3"'
    example_three: It is too big

Note the double quation marks. Is there any way to get the produced YAML on one line, like, `example_two: It is > 3`, without it breaking into a new line?

**Comment by MichaelHoste** [comment]
Hi @robinvdijk 

I can't seem to reproduce this behaviour.
I created these lines in the source language:

```
en:   
  example_one: It is equal to 3
  example_two: It is > 3
  example_three: It is too big
```

Then I synced and it didn't change the `en.yml` file.

After translation and "sync" again, the `translation.fr.yml` got this:

```
fr:
  example_one: C'est égal à 3
  example_two: C'est > 3
  example_three: C'est trop grand
```

So everything seems right.

Can you give me the exact lines in your project that creates this behaviour?
If you want, you can send them to michael@translation.io

Also, I'm not sure to understand if this behaviour happens in your source or translated YAML files:

```
example_two: It is
  > 3
```
