### ISSUE TITLE
Need a suggestion on how to keep the source pluralization clean

### ISSUE THREAD

**Issue by syakovyn** [translation/rails#40]
Hi guys,

I met the following issue today. I have a plural key for a number of students in English (source locale) in which it makes perfect sense:
```yaml
        students_count:
          one: '1 student'
          other: "%{count} students"
```

However, in order to have it translated into Arabic, I need to add a few more keys to the English translation file:
```yaml
        students_count:
          one: "1 student"
          two: "%{count} students"
          few: "%{count} students"
          many: "%{count} students"
          other: "%{count} students"
```
in order to have them appeared in Arabic locale in translations.io.

Could you suggest a way to avoid adding redundant keys to the English translation YML file?

Thanks,
Serhiy

**Comment by MichaelHoste** [comment]
Hi Serhiy,

As you noticed, `zero`, `one`, `two`, `few`, `many` and `other` are special keywords for Ruby on Rails I18n system to deal with plurals: https://guides.rubyonrails.org/i18n.html#pluralization

The thing is, since each language is different regarding pluralization, and English (the most common source language) only uses `one` and `other` (also `zero` but it's optional), you should add placeholders for other plural forms instead of leaving them empty. That's why you have redundant keys in the English YAML file.

You can even add some comments in the "non-english" plural forms to guide your translators: 

```yaml
students_count:
  zero:  '0 students'
  one:   '1 student'
  two:   '2 students [NOTE: TRANSLATE WHEN "TWO" PLURAL FORM IS USEFUL]'
  few:   '%{count} students [NOTE: TRANSLATE WHEN "FEW" PLURAL FORM IS USEFUL]'
  many:  '%{count} students [NOTE: TRANSLATE WHEN "MANY" PLURAL FORM IS USEFUL]'
  other: '%{count} students'
```

You can also give global instructions to the translators, or add a special "don't translate" tag using a filter like `.few` on the translation interface that will filter all of them.

I know that it's not a very clean way to work, but we can't automate this during the "sync", because `zero`, `one`, `two`, (...) are not special keys. They are just regular YAML keys, and Rails deals with them in a special way using conventions. Nothing prevents you from using a `few` key elsewhere in you YAML file without any intention to use plurals. And we don't want to mess with that.

What we usually do, is to mix YAML and GetText syntaxes in our projects, and the GetText way to pluralize is way nicer:

```ruby
# Pluralization
n_("Singular text", "Plural text", number)
```

GetText pluralizations are easy to write and are grouped in a single segment.
The translation interface will adapt depending on the target language (1, 2, 3 or 4 plural forms):

![Screenshot 2020-11-26 at 00 17 01](https://user-images.githubusercontent.com/529357/104477452-6961d380-55c1-11eb-980a-691ceb46d7c4.png)

It should be easier to code (just write it in English) and easier for the translator to understand (we hide in the interface plural forms that are not useful)

I hope it helped.
