### ISSUE TITLE
ignore specific files

### ISSUE THREAD

**Issue by skyporter** [translation/rails#51]
Your documentation explain how to ignore specific keys, but what about a config to ignore specific **files** ?

**Comment by MichaelHoste** [comment]
Hi @skyporter,

Actually, YAML files are almost always prefixed by one, or maybe a couple of keys, but not more.

So if you want to completely ignore a YAML file you can add something like this:

```ruby
config.ignored_key_prefixes = [
    'root_key_of_your_yaml_file.', # don't forget the trailing dot
 ]
```

If you happen to have a lot of first-level keys in your YAML file, you can still do something like this:

```ruby
config.ignored_key_prefixes = YAML.load(File.read('config/locales/ignored.en.yml'))['en'].keys.collect { |k| "#{k}." }
# => ["admin.", "enumerize.", "activerecord."]
```

It's not "neat" but it should work too.

**Comment by skyporter** [comment]
Hi,

Thanks for the alternative suggestions, unfortunately not applicable to my case as I have a file that only contains backend translations. 

For example, I have a `Customer` model which should be only translated in only one language. I manage that by storing "customers keys" on a dedicated file `backend-activerecord.fr.yml`:
```yaml
fr:
  activerecord:
    models:
      customer:
        one: "Fiche client"
        other: "Fiches clients"
```

and my generic `activerecord.fr.yml` file contain all others keys:
```yaml
fr:
  activerecord:
    models:
      user: Utilisateur
      ...
```

As suggested, my only alternative with translation.io is to do that:
```ruby
  config.ignored_key_prefixes = [
    "activerecord.models.customer.",
    "activerecord.attributes.customer."
  ]
```
It would have been easier with the exclusion of the file.
